feat: Introduce error interceptor
monstar-lab-oss/KMP-Template pull request #4
Opened 2024-03-20 10:23 UTC by naiemmlbd

2024-03-20 10:37 UTC, ShaQib07 commented on composeApp/src/commonMain/kotlin/data/network/ApiDefinition.kt
> +        const val username = "username"
use all uppercase letters while declaring constants.
const val USERNAME = "username"

2024-03-20 10:37 UTC, ShaQib07 commented on composeApp/src/commonMain/kotlin/data/network/ApiErrorInterceptor.kt
> +}
Add new line

2024-03-20 10:37 UTC, ShaQib07 commented on composeApp/src/commonMain/kotlin/data/network/ApiServiceImpl.kt
> +        throw ApiErrorException(HttpStatusCode.BadRequest,"Bad ")
Are you throwing this error for test purpose?

2024-03-20 10:37 UTC, ShaQib07 commented on composeApp/src/commonMain/kotlin/presentation/feature/login/LoginContract.kt
> + * passed to the coordinator to handle
Replace coordinator with viewmodel

2024-03-20 11:16 UTC, ShaQib07 approved these changes

2024-03-22 11:07 UTC, levinzonr requested changes
Left some comments :)
When it comes to the error handling I would prefer to it to be closer to what we have in the Android Template now
```
sealed interface ErrorModel {

    data class ApiError(val exception: ApiException) : ErrorModel

    sealed class Connection : ErrorModel {
        object Timeout : Connection()
        object IOError : Connection()
        object UnknownHost : Connection()
    }

    data class Unknown(val throwable: Throwable) : ErrorModel
}
```

2024-03-22 11:07 UTC, levinzonr commented on composeApp/src/commonMain/kotlin/di/ApiErrorValidator.kt
> +}
DI package seems like not the best place to store something like this

2024-03-22 11:07 UTC, levinzonr commented on composeApp/src/commonMain/kotlin/di/NetworkModule.kt
> +                        ApiErrorInterceptor().validateResponse(exceptionResponse)
What's the point of and Interface if we just create an instance of a class extending it? Should we try injecting an interface instead?

2024-03-22 11:07 UTC, levinzonr commented on composeApp/src/commonMain/kotlin/domain/usecase/LoginUseCase.kt
> -        .flowOn(Dispatchers.Default)
No point in this running as flow I think, can be just suspend function

2024-03-22 11:07 UTC, levinzonr commented on composeApp/src/commonMain/kotlin/presentation/model/ErrorModel.kt
> +}
can be sealed class with a message param in constructor

2024-03-22 11:07 UTC, levinzonr commented on composeApp/src/commonMain/kotlin/presentation/model/ErrorModel.kt
> +}
Or keep an interface, but then lets maybe make `message` an extension property.

2024-03-22 11:07 UTC, levinzonr commented on composeApp/src/commonMain/kotlin/data/network/errorhandling/ApiErrorInterceptor.kt
> +        }
This when statement doesn't seem that necessary to me, all it does is checking the code and putting it right back to another class.  The message can be an extension function based on the status code and it should not be hardcoded (if it is meant for UI that is)

2024-03-22 11:07 UTC, levinzonr commented on composeApp/src/commonMain/kotlin/data/network/ApiServiceImpl.kt
> +            setBody(mapOf(USERNAME to userName, PASSWORD to pass))
Why not create a dedicated DTO for this and use Kotlin serialization?

2024-03-22 11:13 UTC, levinzonr commented on composeApp/src/commonMain/kotlin/data/network/errorhandling/ApiErrorInterceptor.kt
> +        }
I think what we really should do here is to try and convert non 200 responses and their response bodies into domain error exception. I.e something like that
```data class ApiException(
    val code: Int,
    val displayableMessage: String,
    val loggableMessage: String
) : IOException(displayableMessage)
```

2024-03-27 07:25 UTC, naiemmlbd commented on composeApp/src/commonMain/kotlin/domain/usecase/LoginUseCase.kt
> -        .flowOn(Dispatchers.Default)
Flow provides lifecycle-aware operations like **onStart** and **onCompletion**, allowing for actions at the beginning and end of the flow's lifecycle, such as displaying and concealing progress indicators.

2024-03-27 10:41 UTC, levinzonr commented on composeApp/src/commonMain/kotlin/domain/usecase/LoginUseCase.kt
> -        .flowOn(Dispatchers.Default)
you can do the same in the beginning and in the end of the suspend call. I feel like this complicates things in various of ways. 
- The flow is very powerful tool, and using its APIs for just one emit call is an overkill
- It doesn't make the code more readable, onCompleteion in this scenario is the same as collect { }

2024-04-02 07:50 UTC, levinzonr approved these changes

2024-04-02 07:57 UTC, merged