Feat/androidx viewmodel multiplatform
monstar-lab-oss/KMP-Template pull request #8
Opened 2024-04-11 13:01 UTC by levinzonr

2024-04-16 01:41 UTC, aslamhossin approved these changes

2024-04-22 06:41 UTC, naiemmlbd approved these changes
LGTM!

2024-04-25 08:37 UTC, aslamhossin commented
please ensure that KMMViewModelSwiftUI is not used within the iOS module.

2024-04-26 09:39 UTC, ShaQib07 requested changes

2024-04-26 09:39 UTC, ShaQib07 commented on composeApp/src/commonMain/kotlin/di/KoinCommon.kt
We've extracted the modules to different files.
This file will only contain `initKoin()` function.
May be it was a merge issue.

2024-04-26 09:42 UTC, levinzonr commented on composeApp/src/commonMain/kotlin/di/KoinCommon.kt
Yeah most likely! Thanks for pointing that out

2024-04-26 10:29 UTC, levinzonr commented on composeApp/src/commonMain/kotlin/di/KoinCommon.kt
Fixed

2024-04-26 10:36 UTC, ShaQib07 requested changes

2024-04-26 10:36 UTC, ShaQib07 commented on composeApp/src/commonMain/kotlin/di/KoinCommon.kt
> +}
Missing new line

2024-04-26 10:36 UTC, ShaQib07 commented on composeApp/src/commonMain/kotlin/di/modules/ViewModelsModule.kt
> +}
Missing new line

2024-04-26 10:36 UTC, ShaQib07 commented on composeApp/src/commonMain/kotlin/presentation/feature/home/HomeViewModelProvider.kt
> +}
Missing new line

2024-04-26 10:36 UTC, ShaQib07 commented on iosApp/Podfile.lock
This file should be in the gitignore

2024-04-26 10:36 UTC, ShaQib07 commented on iosApp/iosApp.xcodeproj/xcshareddata/xcschemes/iosApp.xcscheme
This file should be in the gitignore

2024-04-26 11:05 UTC, levinzonr commented on composeApp/src/commonMain/kotlin/di/modules/ViewModelsModule.kt
> +}
fxied

2024-04-26 11:05 UTC, levinzonr commented on composeApp/src/commonMain/kotlin/presentation/feature/home/HomeViewModelProvider.kt
> +}
fixed

2024-04-26 11:16 UTC, levinzonr commented on iosApp/Podfile.lock
it already is, probably not picked up due to a broken path, fixed

2024-04-26 11:16 UTC, levinzonr commented on iosApp/iosApp.xcodeproj/xcshareddata/xcschemes/iosApp.xcscheme
fixed

2024-04-26 11:36 UTC, ShaQib07 approved these changes
LGTM

2024-04-26 12:59 UTC, ShaQib07 reviewed
However, this ViewModel doesn't work properly with SwiftUI yet.
I guess it'd be better If we draft this PR for now.

2024-04-30 07:46 UTC, ShaQib07 commented
Findings:
There's no issue with the ViewModel it seems.
The issue is with the StateFlow which isn't working with swift UI.
Previously we were using KMMViewModel's Mutable StateFlow with nativeCoroutine annotation.
But the default kotlin's MutableStateFlow ain't working like before.

cc: @aslamhossin

2024-04-30 08:03 UTC, levinzonr commented
Think it should work together with SKIA, in that repo where androidx View model was used there is also SKIA 

Let's verify once SKIA work is merged

2024-05-09 09:03 UTC, levinzonr commented
Closing in favour of https://github.com/monstar-lab-oss/KMP-Template/pull/11

2024-05-09 09:03 UTC, closed without merging